name: widget_with_codeview
description: A widget with side-by-side source code view.
version: 3.1.0
homepage: https://github.com/X-Wei/widget_with_codeview

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_speed_dial: ^7.0.0
  google_fonts: ^8.0.1
  selectable: ^0.5.2
  string_scanner: ^1.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
