name: flutter_catalog
description: An app showcasing Flutter components, with side-by-side source code view.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.5.2+30

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.2
  english_words: ^3.1.3
  firebase_analytics: ^1.1.0
  firebase_auth: ^0.6.6
  firebase_database: ^1.0.5
  firebase_ml_vision: ^0.2.1
  firebase_storage: ^1.0.4
  flutter_gallery_assets: ^0.1.6
  flutter_markdown: ^0.2.0
  flutter_webview_plugin: ^0.3.0
  fluttertoast: ^2.1.0
  google_sign_in: ^3.2.4
  image_picker: ^0.4.12
  local_auth: ^0.3.1
  path_provider: ^0.4.1
  shared_preferences: ^0.4.3
  transparent_image:
  url_launcher: ^3.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # Note: when new assets are added, have to run `flutter clean` to see 
  # changes take effect.
  assets:
    # *Tip*: keep the slash at the end of folder path adds all files to 
    # assets. Note: this doesn't work with subfolders. 
    # c.f. https://github.com/flutter/flutter/issues/4890#issuecomment-407327749
    - lib/routes/
    - res/images/
    - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
