name: flutter_catalog
description: An app showcasing Flutter components, with side-by-side source code view.

# *Note*: when version change, remember to also update constants.dart.
version: 2.5.2+53

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_floatactionbuttons: 0.1.0
  async: ^2.4.0
  backdrop: 0.3.2
  cached_network_image: 2.2.0+1
  charts_flutter: 0.9.0
  cloud_firestore: 0.13.6
  english_words: 3.1.5
  extended_image: 0.9.0
  firebase_analytics: 5.0.14
  firebase_auth: 0.16.1
  firebase_core: 0.4.5
  firebase_database: 3.1.6
  firebase_ml_vision: 0.9.4
  firebase_storage: 3.1.6
  flutter_bloc: 4.0.0
  flutter_gallery_assets: 0.1.9+2
  flutter_markdown: 0.4.1
  flutter_webview_plugin: 0.3.11
  fluttertoast: 4.0.1
  google_sign_in: 4.5.1
  hive_flutter: 0.3.0+2
  hive: 1.4.1+1
  http: 0.12.1
  image_picker: 0.6.7
  local_auth: 0.6.2+3
  lottie: ^0.3.3
  package_info: 0.4.0+18
  path_provider: 1.6.9
  path: 1.6.4
  provider: 4.1.2
  scoped_model: 1.0.1
  sembast: 2.4.4+1
  shared_preferences: 0.5.7+3
  sqflite: 1.3.0+2
  substring_highlight: 0.1.2
  transparent_image: 1.0.0
  url_launcher: 5.4.10
  widget_with_codeview: 1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 0.7.0+2
  build_runner: 1.10.0

dependency_overrides:
  dartx: ^0.3.0
  characters: ^0.5.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # Note: when new assets are added, have to run `flutter clean` to see 
  # changes take effect.
  assets:
    # *Tip*: keep the slash at the end of folder path adds all files to 
    # assets. Note: this doesn't work with subfolders. 
    # c.f. https://github.com/flutter/flutter/issues/4890#issuecomment-407327749
    - lib/routes/
    - res/images/
    - res/lottie/
    - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp
  
  fonts:
    - family: monospace
      fonts:
        - asset: res/DroidSansMono.ttf