name: flutter_catalog
description: An app showcasing Flutter components, with side-by-side source code view.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.3.1+41

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_floatactionbuttons: '0.1.0'
  async: '^2.2.0'
  backdrop: '0.1.8'
  cloud_firestore: '0.12.6'
  english_words: '3.1.5'
  firebase_analytics: '3.0.3'
  firebase_auth: '0.11.1+7'
  firebase_database: '3.0.3'
  firebase_ml_vision: '0.9.0+3'
  firebase_storage: '3.0.2'
  flutter_bloc: '0.18.3'
  flutter_gallery_assets: '0.1.9+2'
  flutter_markdown: '0.2.0'
  flutter_webview_plugin: '0.3.5'
  fluttertoast: '3.1.0'
  google_sign_in: '4.0.2'
  image_picker: '0.6.0+11'
  local_auth: '0.5.2+4'
  package_info: '0.4.0+4'
  path: '^1.6.2'
  path_provider: '1.1.0'
  provider: '3.0.0+1'
  scoped_model: '1.0.1'
  sembast: '2.0.1'
  sqflite: '1.1.6+3'
  shared_preferences: ' 0.5.3+1'
  transparent_image: '1.0.0'
  url_launcher: '5.0.3'
  widget_with_codeview: '1.0.1'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # Note: when new assets are added, have to run `flutter clean` to see 
  # changes take effect.
  assets:
    # *Tip*: keep the slash at the end of folder path adds all files to 
    # assets. Note: this doesn't work with subfolders. 
    # c.f. https://github.com/flutter/flutter/issues/4890#issuecomment-407327749
    - lib/routes/
    - res/images/
    - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
