name: flutter_catalog
description: An app showcasing Flutter components, with side-by-side source code view.

# *Note*: when version change, remember to also update constants.dart.
version: 3.1.1+80

environment:
  sdk: ">=2.13.0 <3.0.0"

publish_to: none

dependencies:
  animated_radial_menu: ^0.0.1
  animated_text_kit: ^4.2.1
  animations: ^2.0.1
  async: null
  backdrop: ^0.7.1
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  charts_flutter: ^0.12.0
  cloud_firestore: ^3.1.5
  cloud_firestore_web: ^2.3.0
  convex_bottom_bar: ^3.0.0
  day_night_switcher: ^0.2.0+1
  edge_detection: ^1.0.7
  english_words: ^4.0.0
  extended_image: ^6.0.1
  feature_discovery: ^0.14.0
  ffi: ^1.1.2
  firebase_analytics: ^9.0.4
  firebase_analytics_web: ^0.4.0+4
  firebase_auth: ^3.0.1
  firebase_auth_web: ^3.0.0
  firebase_core: ^1.4.0
  firebase_core_web: ^1.1.0
  firebase_database: ^9.0.4
  firebase_storage: ^10.0.1
  firebase_storage_web: ^3.0.0
  fl_chart: ^0.40.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_gallery_assets: ^1.0.2
  flutter_markdown: ^0.6.9
  flutter_radar_chart: ^0.2.0
  flutter_riverpod: ^1.0.3
  flutter_slidable: ^1.2.0
  flutter_state_notifier: ^0.7.0
  flutter_webview_plugin: ^0.4.0
  fluttertoast: ^8.0.7
  freezed_annotation: ^1.1.0
  google_fonts: ^2.1.0
  google_ml_kit: ^0.7.0
  google_sign_in: ^5.0.5
  graphview: ^1.1.1
  heatmap_calendar:
    git:
      url: https://github.com/CouldI/flutter_heatmap_calendar.git
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  image: ^3.0.2
  image_picker: ^0.8.2
  intl: ^0.17.0
  local_auth: ^1.1.6
  lottie: ^1.1.0
  markdown: ^4.0.1
  new_gradient_app_bar:
    git:
      url: https://github.com/GUIKAR741/NewGradientAppBar.git
  package_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.2
  photo_view: ^0.13.0
  provider: ^6.0.2
  scoped_model: ^2.0.0-nullsafety.0
  sembast: ^3.1.0+2
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  sqflite: ^2.0.0+3
  state_notifier: ^0.7.0
  substring_highlight: ^1.0.33
  transparent_image: ^2.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.9
  video_player: ^2.1.12
  widget_with_codeview: ^2.0.0-nullsafe

dev_dependencies:
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.0
  freezed: ^1.1.0
  hive_generator: ^1.1.0
  json_serializable: null
  lint: ^1.5.3

# Cf. https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "res/images/launcher_icon.png"

# Cf. https://pub.dev/packages/flutter_native_splash
flutter_native_splash:
  color: "#f6f6f6"
  image: res/images/splash_screen.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # Note: when new assets are added, have to run `flutter clean` to see
  # changes take effect.
  assets:
    # *Tip*: keep the slash at the end of folder path adds all files to
    # assets. Note: this doesn't work with subfolders.
    # c.f. https://github.com/flutter/flutter/issues/4890#issuecomment-407327749
    - lib/routes/
    - lib/routes/data/
    - res/images/
    - res/lottie/
    - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp
