name: flutter_catalog
description: An app showcasing Flutter components, with side-by-side source code view.

version: 3.7.2+100

environment:
  sdk: ">=3.3.3 <4.0.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  animated_radial_menu: ^0.0.1
  animated_text_kit: ^4.2.2
  animations: ^2.0.11
  async: ^2.11.0
  backdrop: ^0.9.1
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  chat_gpt_sdk: ^3.0.4
  cloud_firestore: ^4.17.0
  cloud_firestore_web: ^3.12.0
  community_charts_flutter: ^1.0.2
  community_material_icon: ^5.9.55
  convex_bottom_bar: ^3.2.0
  day_night_switcher: ^0.2.0+1
  device_preview: ^1.1.0
  device_preview_screenshot: ^1.0.0
  edge_detection: ^1.1.3
  english_words: ^4.0.0
  extended_image: ^8.2.0
  feature_discovery: ^0.14.1
  ffi: ^2.1.2
  firebase_analytics: ^10.10.2
  firebase_analytics_web: ^0.5.7+2
  firebase_auth: ^4.19.2
  firebase_auth_web: ^5.11.2
  firebase_core: ^2.30.0
  firebase_core_web: ^2.15.0
  firebase_crashlytics: ^3.5.2
  firebase_database: ^10.5.2
  firebase_storage: ^11.7.2
  firebase_storage_web: ^3.9.2
  firebase_ui_auth: ^1.13.1
  fl_chart: ^0.67.0
  flutter_bloc: ^8.1.5
  flutter_gallery_assets: ^1.0.2
  flutter_heatmap_calendar: ^1.0.5
  flutter_highlight: ^0.7.0
  flutter_markdown: ^0.6.23
  flutter_quill: ^9.3.7
  flutter_radar_chart: ^0.2.1
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.0
  flutter_state_notifier: ^1.0.0
  flutter_whatsnew:
    path: packages/flutter_whatsnew-master
  fluttertoast: ^8.2.5
  freezed_annotation: ^2.4.1
  google_fonts: ^5.1.0
  google_ml_kit: ^0.17.0
  google_mobile_ads: ^5.0.0
  google_sign_in: ^6.2.1
  graphview: ^1.2.0
  heatmap_calendar:
    git:
      url: https://github.com/CouldI/flutter_heatmap_calendar.git
  hidable: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  image: ^4.1.7
  image_picker: ^1.1.0
  in_app_purchase: ^3.2.0
  in_app_review: ^2.0.9
  intl: ^0.18.1
  introduction_screen: ^3.1.14
  like_button: ^2.0.5
  local_auth: ^2.2.0
  lottie: ^3.1.0
  markdown: ^7.2.2
  package_info_plus: ^7.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  provider: ^6.1.2
  scoped_model: ^2.0.0
  selectable: ^0.3.1
  sembast: ^3.7.1
  share_plus: ^8.0.3
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sqflite: ^2.3.3
  state_notifier: ^1.0.0
  substring_highlight: ^1.0.33
  # super_editor: ^0.2.2 TODO: add back when it depends on http ^1.0.0
  transparent_image: ^2.0.1
  tuple: ^2.0.2
  url_launcher: ^6.2.6
  video_player: ^2.8.6
  webview_flutter: ^4.7.0
  widget_with_codeview: ^3.1.0
  youtube_player_iframe: ^5.1.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  lint: ^2.3.0

# $ dart run flutter_launcher_icons
# Cf. https://pub.dev/packages/flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: res/images/app_icon.png

# $ dart run flutter_native_splash:create
# Cf. https://pub.dev/packages/flutter_native_splash
flutter_native_splash:
  color: "#f6f6f6"
  image: res/images/app_icon.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # Note: when new assets are added, have to run `flutter clean` to see
  # changes take effect.
  assets:
    - CHANGELOG.md
    # *Tip*: keep the slash at the end of folder path adds all files to
    # assets. Note: this doesn't work with subfolders.
    # c.f. https://github.com/flutter/flutter/issues/4890#issuecomment-407327749
    - lib/routes/
    - lib/routes/data/
    - res/images/
    - res/lottie/
    - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp
    - screenshots/Screenshot_1541613187.png
    - screenshots/Screenshot_1541613193.png
    - screenshots/Screenshot_1541613197.png
