name: flutter_whatsnew
description: A new Flutter package to show updates to users.
version: 1.0.5+2
# author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/fluttercommunity/flutter_whatsnew
maintainer: Rody Davis (@rodydavis)

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
